name: env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alsa-lib=1.2.14
  - aom=3.9.1
  - attr=2.5.2
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.9.9
  - cairo=1.18.4
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - double-conversion=3.3.1
  - expat=2.7.1
  - ffmpeg=8.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freeglut=3.4.0
  - freetype=2.14.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.44.3
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - glslang=16.0.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - harfbuzz=12.1.0
  - hdf5=1.14.6
  - icu=75.1
  - imath=3.2.1
  - intel-gmmlib=22.8.2
  - intel-media-driver=25.3.4
  - jasper=4.2.8
  - krb5=1.21.3
  - lame=3.100
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - level-zero=1.24.3
  - libabseil=20250512.1
  - libaec=1.1.3
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libass=0.17.4
  - libavif16=1.3.0
  - libblas=3.9.0
  - libboost=1.86.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.76
  - libcblas=3.9.0
  - libclang-cpp21.1=21.1.2
  - libclang13=21.1.2
  - libcups=2.3.3
  - libcurl=8.15.0
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.86.0
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.1
  - libjxl=0.11.1
  - libkrb5=1.21.3
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm21=21.1.2
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopencv=4.12.0
  - libopenvino=2025.2.0
  - libopenvino-auto-batch-plugin=2025.2.0
  - libopenvino-auto-plugin=2025.2.0
  - libopenvino-hetero-plugin=2025.2.0
  - libopenvino-intel-cpu-plugin=2025.2.0
  - libopenvino-intel-gpu-plugin=2025.2.0
  - libopenvino-intel-npu-plugin=2025.2.0
  - libopenvino-ir-frontend=2025.2.0
  - libopenvino-onnx-frontend=2025.2.0
  - libopenvino-paddle-frontend=2025.2.0
  - libopenvino-pytorch-frontend=2025.2.0
  - libopenvino-tensorflow-frontend=2025.2.0
  - libopenvino-tensorflow-lite-frontend=2025.2.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=18.0
  - libprotobuf=6.31.1
  - librsvg=2.60.0
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.9
  - libtiff=4.7.1
  - libudev1=257.9
  - libunwind=1.8.3
  - liburing=2.12
  - libusb=1.0.29
  - libuuid=2.41.2
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpl=2.15.0
  - libvpx=1.14.1
  - libvulkan-loader=1.4.313.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.15.0
  - libxml2-16=2.15.0
  - libzlib=1.3.1
  - lmdb=0.9.31
  - lz4-c=1.10.0
  - mpfr=4.2.1
  - mpg123=1.32.9
  - ncurses=6.5
  - nomkl=3.0
  - numpy-base=2.1.3
  - ocl-icd=2.3.3
  - openblas=0.3.30
  - openblas-devel=0.3.30
  - opencl-headers=2025.06.13
  - opencv=4.12.0
  - openexr=3.4.0
  - openh264=2.6.0
  - openjph=0.24.1
  - openldap=2.6.10
  - openssl=3.5.4
  - pango=1.56.4
  - pcre2=10.46
  - pip=25.2
  - pixman=0.46.4
  - pthread-stubs=0.3
  - pugixml=1.15
  - pulseaudio-client=17.0
  - py-opencv=4.12.0
  - python=3.10.18
  - python_abi=3.10
  - qt6-main=6.9.3
  - rav1e=0.7.1
  - readline=8.3
  - sdl2=2.32.56
  - sdl3=3.2.22
  - shaderc=2025.4
  - snappy=1.2.2
  - spirv-tools=2025.1
  - sqlite=3.50.2
  - svt-av1=3.1.2
  - tbb=2022.0.0
  - tk=8.6.15
  - wayland=1.24.0
  - wayland-protocols=1.45
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.15
    - aiosignal==1.4.0
    - annotated-types==0.7.0
    - anyio==4.12.0
    - async-timeout==5.0.1
    - attrs==25.3.0
    - bio==1.8.1
    - biopython==1.79
    - biothings-client==0.4.1
    - bottleneck==1.4.2
    - certifi==2025.8.3
    - charset-normalizer==3.4.3
    - click==8.3.0
    - contourpy==1.3.2
    - cycler==0.12.1
    - cython==3.1.4
    - decorator==4.4.2
    - einops==0.8.1
    - exceptiongroup==1.3.1
    - filelock==3.19.1
    - fonttools==4.60.1
    - frozenlist==1.7.0
    - fsspec==2025.9.0
    - gitdb==4.0.12
    - gitpython==3.1.45
    - gprofiler-official==1.0.0
    - griddataformats==1.0.2
    - gudhi==3.11.0
    - h11==0.16.0
    - h5py==3.14.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - hypothesis==6.148.7
    - idna==3.10
    - iniconfig==2.3.0
    - jinja2==3.1.6
    - joblib==1.5.2
    - kiwisolver==1.4.9
    - lightning==2.5.5
    - lightning-utilities==0.15.2
    - llvmlite==0.45.1
    - markupsafe==3.0.3
    - matplotlib==3.10.6
    - mda-xdrlib==0.2.0
    - mdanalysis==2.9.0
    - mdanalysistests==2.9.0
    - mmtf-python==1.1.3
    - mpmath==1.3.0
    - mrcfile==1.5.4
    - msgpack==1.1.2
    - multidict==6.6.4
    - mygene==3.2.2
    - networkx==3.4.2
    - numba==0.62.1
    - numexpr==2.11.0
    - numpy==2.1.3
    - nvidia-cublas-cu12==12.8.4.1
    - nvidia-cuda-cupti-cu12==12.8.90
    - nvidia-cuda-nvrtc-cu12==12.8.93
    - nvidia-cuda-runtime-cu12==12.8.90
    - nvidia-cudnn-cu12==9.10.2.21
    - nvidia-cufft-cu12==11.3.3.83
    - nvidia-cufile-cu12==1.13.1.3
    - nvidia-curand-cu12==10.3.9.90
    - nvidia-cusolver-cu12==11.7.3.90
    - nvidia-cusparse-cu12==12.5.8.93
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.27.3
    - nvidia-nvjitlink-cu12==12.8.93
    - nvidia-nvtx-cu12==12.8.90
    - packaging==25.0
    - pandas==2.3.2
    - pillow==11.3.0
    - platformdirs==4.4.0
    - pluggy==1.6.0
    - pooch==1.8.2
    - pot==0.9.6.post1
    - propcache==0.3.2
    - protobuf==6.32.1
    - psutil==7.1.0
    - pydantic==2.11.9
    - pydantic-core==2.33.2
    - pygments==2.19.2
    - pynndescent==0.5.13
    - pyparsing==3.2.5
    - pytest==9.0.2
    - python-dateutil==2.9.0.post0
    - pytorch-lightning==2.5.5
    - pytz==2025.2
    - pyyaml==6.0.3
    - qpsolvers==4.8.1
    - quadprog==0.1.13
    - rdkit==2025.9.3
    - requests==2.32.5
    - scikit-learn==1.7.2
    - scipy==1.15.3
    - sentry-sdk==2.39.0
    - setuptools==72.1.0
    - six==1.17.0
    - smmap==5.0.2
    - sortedcontainers==2.4.0
    - sympy==1.14.0
    - threadpoolctl==3.6.0
    - tomli==2.3.0
    - torch==2.8.0
    - torch-cluster==1.6.3
    - torch-geometric==2.6.1
    - torch-geometric-temporal==0.56.2
    - torch-scatter==2.1.2
    - torch-sparse==0.6.18
    - torch-spline-conv==1.2.2
    - torchjd==0.7.0
    - torchmetrics==1.8.2
    - torchvision==0.23.0
    - tqdm==4.67.1
    - triton==3.4.0
    - typing-extensions==4.15.0
    - typing-inspection==0.4.2
    - tzdata==2025.3
    - umap-learn==0.5.9.post2
    - urllib3==2.5.0
    - wandb==0.22.1
    - wheel==0.45.1
    - yarl==1.20.1
prefix: /home/binal1/miniconda3/envs/env
